### ISSUE TITLE
[HELP WANTED]  An error occerd on Windows

### ISSUE THREAD

**Issue by nnahito** [ba0f3/libssh2.nim#11]
Thank you for your wonderful library.
The following error occurred when using the library containing libssh2.nim.

```
\nimble\pkgs\libssh2-0.1.4\libssh2.nim(35, 14) Error: ambiguous identifier: 'SocketHandle' -- use one of the following:
  posix.SocketHandle: SocketHandle
  winlean.SocketHandle: SocketHandle
```

I would appreciate it if you could tell us how to solve this problem.

- My env
    - Windows10
    - Nim Compiler Version 1.6.0 [Windows: amd64]

Thank you very much.

**Comment by ba0f3** [comment]
I'm sorry but it currently doesn't work on Windows, It requires some modifications in order to works, I will do it when I have free time

**Comment by nnahito** [comment]
Thanks for getting back to me!
I see, so it does not currently work on Windows.
I do not have the technical skills to fix it, so I am waiting.
Thank you so much!

**Comment by ba0f3** [comment]
There was a modified version of @Techno-Fox in #5 to make it works with Windows. I'm going to merge it now
