### ISSUE TITLE
Ambiguous identifier: 'Time' --use posix.Time or times.Time

### ISSUE THREAD

**Issue by treeform** [ba0f3/libssh2.nim#3]
I get this error:
```
..\..\..\..\..\..\..\..\C:\Users\me\.nimble\pkgs\libssh2-0.1.0\libssh2.nim(511, 84) 
Error: ambiguous identifier: 'Time' --use posix.Time or times.Time
```
Does this lib work on windows?

**Comment by ba0f3** [comment]
I never tested it on Windows yet. but why do you import posix on windows?

**Comment by treeform** [comment]
libssh2.nim imports it. posix.nim works on windows some-what.

**Comment by ba0f3** [comment]
I think it need a small change. I will check it soon

**Comment by treeform** [comment]
I ended up wrapping ssh.exe with osproc for now: https://github.com/treeform/ssh
I would like to use a real ssh library eventually.

**Comment by Techno-Fox** [comment]
I fixed it. In an issue called Broke Code.

**Comment by ba0f3** [comment]
Thanks, I will check it when I get home
