### ISSUE TITLE
passing flags

### ISSUE THREAD

**Issue by Techno-Fox** [ba0f3/libssh2.nim#6]
Story time. So I started a project in C/C++ but decided to port it to nim-lang (easier development, reading, etc.). That project uses the libssh2 library. I just so happen to need to do sftp operations.

Now in the C/C++ version it was done in this manner. 

sftp_handle = libssh2_sftp_open(sftp_session, sftppath.c_str(),
        LIBSSH2_FXF_WRITE | LIBSSH2_FXF_CREAT | LIBSSH2_FXF_TRUNC,
        LIBSSH2_SFTP_S_IRUSR | LIBSSH2_SFTP_S_IXUSR |
        LIBSSH2_SFTP_S_IRGRP | LIBSSH2_SFTP_S_IXGRP |
        LIBSSH2_SFTP_S_IROTH | LIBSSH2_SFTP_S_IXOTH );

in the nim im trying this :

var sftp_handle = sftp_open(sftp_session, sftpPath,
        LIBSSH2_FXF_WRITE | LIBSSH2_FXF_CREAT | LIBSSH2_FXF_TRUNC,
        LIBSSH2_SFTP_S_IRUSR | LIBSSH2_SFTP_S_IXUSR |
        LIBSSH2_SFTP_S_IRGRP | LIBSSH2_SFTP_S_IXGRP |
        LIBSSH2_SFTP_S_IROTH | LIBSSH2_SFTP_S_IXOTH)

However that is giving the error: 

 Error: type mismatch: got <int literal(2), int literal(8)>
        ... but expected one of: 
        ... proc `|`(a, b: typedesc): typedesc
        ...   first type mismatch at position: 1
        ...   required type for a: typedesc
        ...   but expression '0x00000002' is of type: int literal(2)
        ... expression: 0x00000002 | 0x00000008

so how do I pass those flags and mode?

**Comment by ba0f3** [comment]
Nim does not have `|` operator, you should use `or` instead

**Comment by Techno-Fox** [comment]
I believe that was a bit operator tho to pass multiple flags
